spring:
  datasource:
    url: jdbc:postgresql://localhost:12345/sql
    username: sql
    password: password

server:
  port: 30000
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
    key-store-password: changeit


